data:
    dataset_type: "cached_threedfront"
    encoding_type: "cached_autoregressive_wocm_eval"
    dataset_directory: "./data/input/SAMP_data/"
    annotation_file: "../config/samp/diningrooms_threed_front_splits_sit.csv"
    train_stats: "../data/preprocess_3DFRONTHUMAN_input/diningrooms_preprocess_fuse/dataset_stats_threed_front_diningrooms.txt"
    filter_fn: "no_filtering"
    room_layout_size: "64,64"
    human_contact: True
    human_contact_kinds: 4
    input_all_humans: 'RandomFreeNonOccupiedContactPEOnlyOne'
    masktype: 'layoutfree'
    multimask: False
    eval: True
    interval: -1
    load_once: False
    
network:
    type: "autoregressive_transformer_human_anchor_one_hot"
    n_layers: 4
    n_heads: 8
    query_dimensions: 64
    value_dimensions: 64
    feed_forward_dimensions: 1024
    hidden2output_layer: "autoregressive_mlc"
    hidden_dims: 512
    with_extra_fc: false
    bbox_output: "autoregressive_mlc"
    n_mixtures: 10
    use_room_mask_as_features: true
    contact_as_query: true

feature_extractor:
    name: "resnet18"
    feature_size: 64
    freeze_bn: true
    input_channels: 2

training:
    splits: ["train", "val"]
    epochs: 5000
    steps_per_epoch: 500 
    batch_size: 128
    save_frequency: 50
    optimizer: Adam
    lr: 0.0001
    weight_decay: 0.001

validation:
    splits: ["test"]
    frequency: 50
    batch_size: 128

logger:
    type: "wandb"
    project: "autoregressive_transformer"
