name: mime
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - cython=0.29.21
  - numpy=1.19.1
  - networkx=2.5.1
  - pyrr=0.10.3
  - pyyaml=5.3.1
  - python=3.8
  - pytorch=1.6.0
  - cudatoolkit=10.2
  - torchvision=0.7.0
  - pillow=7.2.0
  - scipy=1.5.2
  - tqdm=4.50.2
  - trimesh=3.8.10
  - matplotlib=3.3.1
  - wxpython=4.0.7
  - pip:
    - simple_3dviz==0.4.0
    - pytorch-fast-transformers==0.4.0
